---
title: "Modern economics workshop on empirical research...for non-economists!"
subtitle: (1) models and language of empirical economics
format: clean-revealjs
author:
  - name: Hyoungchul Kim
    orcid: 0009-0009-3510-097X
    email: hchulkim@wharton.upenn.edu
    affiliations: Wharton, Penn
date: last-modified
---

## Overview 

- This presentation is designed as one of the first sessions for a series of workshops on empirical economics for non-economists.

[Today's goal]{.alert}

- Briefly review what empirical economics is and some key concepts.
- Provide some examples of empirical research.
- Provide some technical jargons used in empirical economics.

## (Brief) What is empirical economics?

- Essentially, any research that involves using real-world data. 
- More formally, using data and economic models to identify and understand certain phenomena in the real world.
- While topics of empirical econmics are vast, its power lies in (mostly) coherent set of tools and tehcniques to understand topics of interest.
- Due to its flexibility, tools and methods from empirical economics are widely used in other fields, such as psychology, sociology, political science, etc.

## Important high-level concept: causal inference

## Example: legalized abortion and crime

## Types of empirical work

## Descriptive

## Structural

## Identification

## Ideal case? Randomized controlled trial (RCT)

## Reduced-form approach

## Structural approach

## What about program evaluation?

## What about quasi-experiments?/natural experiments?

## reduced-form vs. structural?

## Example

### This is a subtitle

Here we have some text that may run over several lines of the slide frame,
depending on how long it is.

- first item 
    - A sub item

Next, we'll brief review some theme-specific components.

- Note that _all_ of the standard Reveal.js
[features](https://quarto.org/docs/presentations/revealjs/)
can be used with this theme, even if we don't highlight them here.

## Additional theme classes

### Some extra things you can do with the clean theme

Special classes for emphasis

- `.alert` class for default emphasis, e.g. [important note]{.alert}.
- `.fg` class for custom colour, e.g. [important note]{.fg style="--col: #e64173"}.
- `.bg` class for custom background, e.g. [important note]{.bg style="--col: #e64173"}.

Cross-references

- `.button` class provides a Beamer-like button, e.g.
[[Summary]{.button}](#sec-summary)

## Want more?

### See our longer demo slides

We've deliberarely kept this template lean, to get you up and running as fast as
possible.

We provide a separate
[demo template](https://github.com/grantmcdermott/quarto-revealjs-clean-demo),
with more examples for integrating code, tables, figures, etc.

  - See the live demo slides
  [here](https://grantmcdermott.com/quarto-revealjs-clean-demo/template.html).

## Summary {#sec-summary}

### A minimalist and elegant presentation theme

The Quarto reveal.js clean theme aims to be a minimalist and elegant presention
theme. Here are some options to get you started:

Add the theme to an existing project.

```{.bash}
quarto install extension grantmcdermott/quarto-revealjs-clean
```

... or, create a new project using this slide deck as a lean template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean
```

... or, create a new project using the demo slide deck as a full template.

```{.bash}
quarto use template grantmcdermott/quarto-revealjs-clean-demo
```
